version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: restaurant-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_platform
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d restaurant_platform']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    name: restaurant_platform_postgres_data