// Mock data for development (replace with database queries when available)
export let mockMediaArticles = [
  {
    id: '1',
    restaurantId: 'pave46',
    title: 'NY Times: Best New Bakery',
    description: '"Pavé brings authentic Parisian pastries to Midtown Manhattan with a level of craftsmanship rarely seen outside of France. Their croissants rival those found on Boulevard Saint-Germain." - Pete Wells, NY Times Food Critic',
    coverImage: '/images/media/nytimes-review.jpg',
    publishDate: new Date('2024-01-15'),
    source: 'New York Times',
    author: 'Pete Wells',
    link: 'https://nytimes.com/pave46-review',
    isPremium: false,
    isPublished: true,
    sortOrder: 0,
  },
  {
    id: '2',
    restaurantId: 'pave46',
    title: 'Michelin Guide 2024',
    description: 'Featured in the prestigious Michelin Guide as a Bib Gourmand recipient, recognizing exceptional food at moderate prices.',
    coverImage: '/images/media/michelin-feature.jpg',
    publishDate: new Date('2024-02-01'),
    source: 'Michelin Guide',
    author: null,
    link: null,
    isPremium: true,
    isPublished: true,
    sortOrder: 1,
  },
  {
    id: '3',
    restaurantId: 'pave46',
    title: 'Eater: Essential NYC Bakeries',
    description: '"The butter lamination at Pavé is nothing short of perfection. This is where New Yorkers come for their morning croissant fix." - Eater NY Essential 38 List',
    coverImage: '/images/media/eater-article.jpg',
    publishDate: new Date('2024-01-20'),
    source: 'Eater NY',
    author: 'Robert Sietsema',
    link: 'https://eater.com/pave46',
    isPremium: false,
    isPublished: true,
    sortOrder: 2,
  },
  {
    id: '4',
    restaurantId: 'pave46',
    title: 'Chef Philippe Interview',
    description: 'Exclusive interview with Executive Chef Philippe about his journey from Lyon to New York and the art of French baking.',
    coverImage: '/images/media/chef-interview.jpg',
    publishDate: new Date('2024-03-01'),
    source: 'Pavé46 Exclusive',
    author: 'Sarah Johnson',
    link: null,
    isPremium: true,
    isPublished: true,
    sortOrder: 3,
  },
  {
    id: '5',
    restaurantId: 'pave46',
    title: 'Time Out: Top 10 Brunch',
    description: '"Skip the tourist traps and head to Pavé for the most authentic French brunch experience in the city. The croque monsieur is life-changing." - Time Out New York',
    coverImage: '/images/media/timeout-review.jpg',
    publishDate: new Date('2024-02-15'),
    source: 'Time Out NY',
    author: 'Emma Orlow',
    link: 'https://timeout.com/nyc/pave46',
    isPremium: false,
    isPublished: true,
    sortOrder: 4,
  },
  {
    id: '6',
    restaurantId: 'pave46',
    title: 'Vogue: Fashion Week Dining',
    description: "Where fashion insiders fuel up during NYFW - an exclusive look at the style set's favorite French café.",
    coverImage: '/images/media/vogue-feature.jpg',
    publishDate: new Date('2024-02-20'),
    source: 'Vogue',
    author: 'Julia Reed',
    link: null,
    isPremium: true,
    isPublished: true,
    sortOrder: 5,
  },
  {
    id: '7',
    restaurantId: 'pave46',
    title: 'WSJ: Business of Bakeries',
    description: '"How Pavé revolutionized the NYC bakery scene with traditional techniques and modern business acumen." - Wall Street Journal Business Section',
    coverImage: '/images/media/wsj-article.jpg',
    publishDate: new Date('2024-03-10'),
    source: 'Wall Street Journal',
    author: 'Michael Chen',
    link: 'https://wsj.com/articles/pave46-bakery',
    isPremium: false,
    isPublished: true,
    sortOrder: 6,
  },
  {
    id: '8',
    restaurantId: 'pave46',
    title: 'Bon Appétit: Secret Menu',
    description: "Discover the off-menu items that regulars order at this Midtown gem, plus Chef Philippe's personal favorites.",
    coverImage: '/images/media/bon-appetit.jpg',
    publishDate: new Date('2024-03-15'),
    source: 'Bon Appétit',
    author: 'Andrew Knowlton',
    link: null,
    isPremium: true,
    isPublished: true,
    sortOrder: 7,
  },
];